### ISSUE TITLE
Order of management commands

### ISSUE THREAD

**Issue by tschale** [Blueshoe/django-hurricane#21]
The execution order of management commands when using `--command` multiple times could be added to the documentation. There might be applications with management commands that depend on a previous one.

**Comment by vvvityaaa** [comment]
Do you mean, that it should be described in the documentation, which commands should be run one after the other, because they depend on each other?

**Comment by tschale** [comment]
I might have an application for which I want multiple management commands to run before it starts. So I use `--command` multiple times. What if my management commands have dependencies on one another? E.g. `mgmt_cmd_1` must run before `mgmt_cmd_2`? Is hurricane executing the commands in the order they are specified? E.g. if I would call it with `python manage.py serve [...] --command mgmt_cmd_1 --command mgmt_cmd_2 [...]`, would my commands be executed in exactly that order? The documentation currently says nothing about it.

**Comment by vvvityaaa** [comment]
Yes, I see your point. It is important to write an extensive description for this situation.
