### ISSUE TITLE
Add documentation of command-flag

### ISSUE THREAD

**Issue by tschale** [Blueshoe/django-hurricane#59]
If I'm not mistaken, the `command`-flag is currently not documented. It should be added in the table with the flags and might have a small section explaining it (I'm mainly thinking about what's happening when the command is specified multiple times).

**Comment by vvvityaaa** [comment]
There is a subsection about the management commands in the User's guide. I think the navigation through the User's guide could be better, for instance, in a form of a content table, where the sections and subsections would be listed. Right now, you need to scroll through the guide to find this section.

**Comment by tschale** [comment]
You're correct @vvvityaaa. I was only looking in the readme of this repo. The table in the user's guide that lists all command options (https://django-hurricane.readthedocs.io/en/latest/usage.html#application-server) differs from the one we list in the readme of this repo. That is probably a quick fix to make them identical (there's something missing in the readme and also something missing in the user's guide). The same holds true for the amqp table (https://django-hurricane.readthedocs.io/en/latest/usage.html#amqp-worker).
And I agree with you that we might want to introduce a table of contents to the user's guide. There is the nav-bar on the left, but still we may want to have a more fine-granular toc.

**Comment by vvvityaaa** [comment]
we discussed it with @Schille, he was saying, that it doesn't make sense to have duplicated documentation. Thus, I will remove the duplicated info from readme and only have all the information in the documentation

**Comment by vvvityaaa** [comment]
@tschale thanks for hint about the missing info in the documentation, I will add all the missing info to the docu

**Comment by tschale** [comment]
Thank you!
